name: Build and Deploy Storybook
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 12.x

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm install
    - name: Build Storybook
      run: npm run build-storybook
    - name: Deploy to Firebase Hosting
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting:chart-storybook
      env: 
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
